#!/usr/bin/env zsh

# this program will show the temperature of a given component and the name of it

# COLOR CODES

# 0 - 20 C -> blue
# 21 - 50 -> purple
# 51 - 70 -> green
# 71 - * -> red

RED="\033[1;31m"
PURPLE="\033[1;35m"
GREEN="\033[1;32m"
BLUE="\033[1;34m"
NOCOLOR="\033[0m"

paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sort -nrk2 | while read line; do
    if [[ "$(awk '{print $3}' <<< "$line")" ]]; then
        t="$(awk '{print $3}' <<< "$line")"
        c="$(awk '{print $1, $2}' <<< "$line")"
    else
        t="$(awk '{print $2}' <<< "$line")"
        c="$(awk '{print $1}' <<< "$line")"
    fi
    ct="$(sed 's/\(.\)..$/.\1°C/' <<< "$t")"
    [[ "$t" -ge 0 && "$t" -le 20000 ]] && PAYLOAD=""$BLUE"$ct""$NOCOLOR"
    [[ "$t" -ge 20001 && "$t" -le 50000 ]] && PAYLOAD=""$PURPLE"$ct""$NOCOLOR"
    [[ "$t" -ge 50001 && "$t" -le 70000 ]] && PAYLOAD=""$GREEN"$ct""$NOCOLOR"
    [[ "$t" -ge 70001 && "$t" -le 100000 ]] && PAYLOAD=""$RED"$ct""$NOCOLOR" 
    paste <(echo "$PAYLOAD") <(echo "$c") --delimiters '\t'
done

