#!/usr/bin/env zsh

# this script was written to help interact with Google Drive for my school work flow
# push --> <file> or <directory>
# pull --> get file or directory

# External Documentation
## https://olivermarshall.net/how-to-upload-a-file-to-google-drive-from-the-command-line/
## https://superuser.com/questions/1293539/gdrive-cli-upload-to-a-certain-folder
## https://www.howtoforge.com/tutorial/how-to-access-google-drive-from-linux-gdrive/

function helper() {
	echo "Hey stop fucking up"
}
function get_id() {
	[[ ! -z "$1" ]] && (gdrive list --query "name contains '$1'" | awk '/'$1'/ {print $1, $3}')
}

function push_file(){
	for element in "$@"; do
		PUSH=`echo "$(get_id unsorted_files)"`
		[[ -d "$element" ]] && (gdrive upload --parent "$PUSH" --recursive "$element";break)
		[[  $(file --mime-type "$1" | sed 's/^[^:]*: //' | grep 'pdf')  ]] && PUSH=`echo "$(get_id PDFs | awk '{print $1}')"`
		[[  $(file --mime-type "$1" | sed 's/^[^:]*: //' | awk '/image/ || /video/')  ]] && PUSH=`echo "$(get_id image_dumping | awk '{print $1}')"`
		[[ -f "$element" ]] && (gdrive upload --parent "$PUSH" "$element")
	done
}

function pull_file() {
	for element in "$@"; do
		BASE=`echo "$(get_id "$element" | head -n 1)"`
		LOCATION=`echo "$BASE" | awk '{print $1}'`
		TYPE=`echo "$BASE" | awk '{print $2}'`
		[[ -z "$BASE" ]] && (echo "Cannot find location of file specified";break)
		# if the file already exists, remove it so we can make room for the new copy
		[[ -f "$element" || -d "$element" ]] && (rm -rf "$element")
		# finding document files and dowloading them
		# gdrive export --mime application/pdf "$LOCATION"
		[[ "$TYPE" == "bin" ]] && (gdrive download "$LOCATION")
		[[ "$TYPE" == "dir" ]] && (gdrive download --recursive "$LOCATION")
		[[ "$(gdrive list --query "name contains '$element'" | grep "doc")" ]] && (gdrive export --mime application/pdf "$LOCATION")
	done

}

function sync_directories(){
	# looks like this feature is quite slow and can conflict with the basic functionality of this script, please do not use
	for element in "$@"; do
		[[ ! -d "$element" ]] && break
		# make sure we take the same approach as we did for files but now we will have hardcoded places where we can sync based on the dir given
		# PDFs are the only needed feature here, more will be added over time
		[[ "$(realpath $element)" == "$(realpath ~/Document/PDFs)" ]] && (DRIVE_PATH=`echo "$(get_id PDFs)"`)
		# misc will go to a misc folder
		ELEMENT_PATH=`echo "$(get_id | awk '{print $1}')"`
		gdrive sync upload "$element" 
	done
}
case $1 in
	push)
		push_file "${@:2}"
		;;
    	pull)
		pull_file "${@:2}"
		;;
	get)
		for element in "${@:2}"; do
			echo "$(get_id "$element" | head -n 1)"
		done
		;;
	sync)
		echo "sync multiple folders"
		;;
	help)
		helper
		;;
esac
